name: boltz_dart
description: A Flutter library for the Boltz dart client
version: 1.0.0+1
homepage: https://github.com/SatoshiPortal/boltz-dart

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.82.2
  meta: ^1.8.0
  uuid: ^4.1.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  archive: ^3.4.10
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  ffigen: ^9.0.0
  test: ^1.24.3
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/

  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true

# flutter_rust_bridge:
#   rust_input: rust/src/api.rs
#   dart_output: lib/bridge_generated.dart
  # dart_decl_output: lib/bridge_generated.dart
