name: boltz_dart
description: Boltz dart client
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.82.3
  meta: ^1.8.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  ffigen: ^9.0.0
  test: ^1.24.9

flutter:
  assets:
    - assets/

  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true

# flutter_rust_bridge:
#   rust_input: rust/src/api.rs
#   dart_output: lib/bridge_generated.dart
  # dart_decl_output: lib/bridge_generated.dart
