[package]
name = "boltz-dart"
authors = ["i5hi <ishi@satoshiportal.com>, mocodesmo <morteza@satoshiportal.com>"]
version = "0.1.2"
edition = "2021"

[lib]
name = "boltzclient"
doctest = false
crate-type = ["staticlib", "cdylib", "lib"] 

[dependencies]
boltz-client = { version = "0.1.2"}
flutter_rust_bridge = "1.82.2"
anyhow = "1.0.68"

[build-dependencies]
flutter_rust_bridge_codegen = { version = "= 1.82.6"  }

[build]
profiler = true

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"



